app/company/__init__.py
from .views import company_

app/company/views.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for, g
from flask_login import login_required,current_user
from app.sql_operation.mysql import *
import base64
from app import db

company_ = Blueprint('company', __name__)

@company_.route("")
@company_.route("/index")
@login_required
def company_index():
	return render_template("company.html",Type = g.user.UserType)

@company_.route("/info")
@login_required
def company_info():
	user = g.user
	user = User.query.filter_by(UserID=user.UserID).first_or_404()
	if user.UserType == "Company":
		consum = Consumer.query.filter_by(ConsumerID=user.UserID).first()
		dec_forms = DecorationForm.query.filter_by(ConsumerID=user.UserID).all()
		user_addresses = UserAddress.query.filter_by(UserID=user.UserID).all()
		order_forms = OrderForm.query.filter_by(UserID=user.UserID).all()


	return redirect(url_for("main.index"))


@company_.route("/change_info", methods=['GET', 'POST'])
@login_required
def company_change_info():
	return

def update_company(id, type, auth, addr, intro):
	sql = ""
	if type != None:
		sql += ",CompanyType='%s'" % type
	if auth != None:
		sql += ", CompanyAuth='%s'" % auth
	if addr != None:
		sql += ", CompanyAddress='%s'" % addr
	if intro != None:
		sql += ",CompanyIntro='%s'" % intro
	sql = sql[1:]
	db.session.execute("update Company set %s where CompanyID=%d" % (sql, id))
	db.session.commit()

# Test ed
@company_.route("/verify", methods=['GET', 'POST'])
@login_required
def company_verify():
	if g.user :
		db.session.execute("update Company set CompanyAuth='Y' where CompanyID=%d" % g.user.UserID)
		db.session.commit()
	return render_template('company_verify.html',Type = g.user.UserType)

@company_.route("/design_scheme", methods=['GET', 'POST'])
@login_required
def company_design_scheme():
	return

#Test ed
@company_.route("/company_orders", methods=['GET', 'POST'])
@login_required
def company_orders():
	design = []
	merchandise = []

	schemes = get_all_success_scheme_byid(g.user.UserID)
	for item in schemes:
		temp = {}
		temp['date'] = str(item[0])
		temp['url'] = 'http://127.0.0.1:5000/designer/scheme/' + str(item[1])
		temp['price'] = '$' + str(item[2])
		temp['name'] = str(item[1])
		temp['designer'] = 'None'
		temp['user'] = item[4]
		design.append(temp)
	order_forms = get_all_succeed_order(g.user.UserID)
	for item in order_forms:
		temp = {}
		temp['date'] = str(item[0])
		temp['url'] = 'http://127.0.0.1:5000/company/furniture/' + str(item[1])
		temp['price'] = '$'+str(item[2])
		temp['name'] = item[3]
		temp['quantity'] = item[4]
		temp['user'] = item[5]
		merchandise.append(temp)
	return render_template('company_order.html', design=design, merchandise=merchandise,Type = g.user.UserType)

def get_all_success_scheme_byid(id):
	company = Company.query.filter_by(CompanyID=id).first()
	if company:
		schemes = db.session.execute("select SubmitTime,DesignScheme.SchemeID,SchemePrice,SchemeDESC,UserName from DesignScheme, CompetitiveBid, DecorationForm, User where "
									 "DesignScheme.SchemeID=CompetitiveBid.SchemeID and CompetitiveBid.DcFormID=DecorationForm.DcFormID "
									 " and DecorationForm.ConsumerID = User.UserID and DesignScheme.CompanyID=%d" % id)
		return schemes
	return None

def get_all_succeed_order(id):
	user = User.query.filter_by(UserID=id).first()
	if user and user.UserType == 'Company':
		order_forms = db.session.execute("select CreateTime,Furniture.FurnitureID,FurniturePrice,FurnitureName,"
										 " OrderItemNum, UserName from Furniture, OrderItem, OrderForm, User where "
										 "Furniture.FurnitureID=OrderItem.FurnitureID and OrderItem.OrderFormID=OrderForm.OrderFormID "
										 " and OrderForm.UserID=User.UserID and Furniture.CompanyID=%d and OrderFormState='Success'" % id)

		return order_forms
	return None

@company_.route("/advertisement", methods=['GET', 'POST'])
@login_required
def company_advertisement():
	return

def get_ad_bycompanyid(id):
	ads = Advertisement.query.filter_by(CompanyID=id).all()
	return ads

# Test ed
@company_.route("/furniture_list", methods=['GET', 'POST'])
@login_required
def company_furniture_list():

	return render_template('company_merchandise.html',Type = g.user.UserType)

def get_all_furniture_list(id):
	goods = Furniture.query.filter_by(CompanyID=id).all()
	return goods

# Test ed
@company_.route("/furniture/<id>", methods=['GET', 'POST'])
def company_furniture(id):
	login_type=''
	g.user = current_user
	if (g.user != None and g.user.is_authenticated):
		login_type = g.user.UserType
	else:
		login_type = None
	# from app.sql_operation.mysql import init_mysql
	# init_mysql()
	class Product():
		def __init__(self, _name, _desc, _price, _intro, _path):
			self.name = _name
			self.description = _desc
			self.price = _price
			self.procedure = _intro
			self.img = _path # "/static/img/product/2.jpg"
	class Comment():
		def __init__(self, _name, _date, _con, _path):
			self.name = _name
			self.time = _date
			self.content = _con
			self.img = _path # "/static/img/client/1.jpg"
	item, company, coms = get_furniture_byid(int(id))
	path = 'app/static/img/product/' + str(item.FurnitureID) + '.jpg'
	path_img = '/static/img/product/' + str(item.FurnitureID) + '.jpg'
	with open(path, "wb") as f:
		f.write(base64.b64decode(item.FurnitureImage))
		f.close()
	product = Product(item.FurnitureName, item.FurnitureDESC, item.FurniturePrice, company.CompanyIntro, path_img)
	comments = []
	for row in coms:
		cpath = 'app/static/img/client/' + str(row[1]) + '.jpg'
		cpath_img = '/static/img/client/' + str(row[1]) + '.jpg'
		with open(cpath, "wb") as f:
			f.write(base64.b64decode(row[0]))
			f.close()
		comment = Comment(row[2], "NO date", row[3], cpath_img)
		comments.append(comment)
	test = "Test"
	return render_template('product.html', product=product, comments=comments, test=test,Type = login_type)

def get_furniture_byid(id):
	item = Furniture.query.filter_by(FurnitureID=id).first()
	company = Company.query.filter_by(CompanyID=item.CompanyID).first()
	comments = db.session.execute("select UserImage,User.UserID, UserName,Content,Rank from User,OrderItem, OrderForm, Comments where "
					   "OrderItem.FurnitureID=%d and OrderItem.OrderFormID=OrderForm.OrderFormID "
					   "and OrderForm.OrderFormID=Comments.OrderFormID and "
					   "User.UserID = OrderForm.UserID " % id)
	return item, company, comments

# Test ed
@company_.route("/my_designer", methods=['GET', 'POST'])
@login_required
def company_my_designer():
    class PDeg():
        def __init__(self):
            self.img = '/static/img/client/1.jpg'
            self.name = "jj"
    items = []
    if g.user and g.user.UserType == "Company":
        people = get_all_designer_byid(g.user.UserID)
        for row in people:
            temp = PDeg()
            cpath = 'app/static/img/client/' + str(row.DesignerID) + '.jpg'
            cpath_img = '/static/img/client/' + str(row.DesignerID) + '.jpg'
            user = User.query.filter_by(UserID=row.DesignerID).first()
            with open(cpath, "wb") as f:
                f.write(base64.b64decode(user.UserImage))
                f.close()
            temp.img = cpath_img
            temp.name = user.UserName
            items.append(temp)
    return render_template('company_designer.html', designers = items,Type = g.user.UserType)


def get_all_designer_byid(id):
	people = Designer.query.filter_by(CompanyID=id).all()
	return people

app/consumer/__init__.py
from .views import consumer_

app/consumer/views.py
# -*- coding: UTF-8 -*-
from flask import Blueprint
from flask import render_template, request, redirect, url_for, g
from flask_login import login_required
from app.sql_operation.mysql import *
from app import db
from flask import g
from flask_login import current_user

consumer_ = Blueprint('consumer', __name__)


@consumer_.route("")
@consumer_.route("/index")
#@login_required
def consumer_index():
	'''
	user = g.user
	user = User.query.filter_by(UserID=user.UserID).first_or_404()
	if user.UserType == "Consumer":
		consum = Consumer.query.filter_by(ConsumerID=user.UserID).first()
		dec_forms = DecorationForm.query.filter_by(ConsumerID=user.UserID).all()
		user_addresses = UserAddress.query.filter_by(UserID=user.UserID).all()
		order_forms = OrderForm.query.filter_by(UserID=user.UserID).all()
	'''
	return render_template("consumer.html", user_name='dyftug',Type = g.user.UserType)


@consumer_.route("/change_info", methods=['GET', 'POST'])
@login_required
def consumer_change_info():

	return render_template('consumer_profile.html',Type = g.user.UserType)

def update_consumer(id, birth, truename, sex, resident):
	sql = ""
	if birth != None:
		sql += ",ConsumerBirth=str_to_date('%s', '%%Y-%%m-%%d')" % birth
	if truename != None:
		sql += ",ConsumerTrueName='%s'" % truename
	if sex != None:
		sql += ",ConsumerSex='%s'" % sex
	if resident != None:
		sql += ",ConsumerResident='%s'" % resident
	sql = sql[1:]
	db.session.execute("update Consumer set %s where ConsumerID=%d" % (sql, id))
	db.session.commit()

@consumer_.route("/add_rec_addr", methods=['GET', 'POST'])
@login_required
def consumer_add_rec_addr():
	return

def insert_useraddress_item(uid, addr):
	newAddr = UserAddress(UserID=uid, DeliveryAddress=addr)
	db.session.add(newAddr)
	db.session.commit()

# test ed
@consumer_.route("/cart", methods=['GET', 'POST'])
@login_required
def consumer_cart():
	'''
	user = g.user
	user = User.query.filter_by(UserID=user.UserID).first_or_404()
	if user.UserType == "Consumer":
		consum = Consumer.query.filter_by(ConsumerID=user.UserID).first()
		dec_forms = DecorationForm.query.filter_by(ConsumerID=user.UserID).all()
		user_addresses = UserAddress.query.filter_by(UserID=user.UserID).all()
		order_forms = OrderForm.query.filter_by(UserID=user.UserID).all()
	'''
	# g.user = User.query.filter_by(UserID=1).first()
	items = []
	user, consumer, order_forms, goods = get_cart_byid(g.user.UserID)
	total = 0
	for item in goods:
		print item
		temp = {}
		path = 'app/static/img/product/' + str(item[2]) + '.jpg'
		path_img = '/static/img/product/' + str(item[2]) + '.jpg'
		with open(path, "wb") as f:
			f.write(base64.b64decode(item[0]))
			f.close()
		temp['img'] = path_img
		temp['price'] = '$' + str(item[1])
		temp['page'] = 'http://127.0.0.1:5000/company/furniture/' + str(item[2])
		temp['name'] = item[3]
		temp['quantity'] = item[4]
		temp['total'] = item[1] * item[4]
		total += int(item[1]) * int(item[4])
		items.append(temp)
	return render_template('cart.html', items=items, subtotal='$'+str(total), total='$'+str(total),Type = g.user.UserType)

def get_cart_byid(id):
	user = User.query.filter_by(UserID=id).first()
	if user and user.UserType == 'Consumer':
		consumer = Consumer.query.filter_by(ConsumerID=user.UserID).first()
		order_forms = OrderForm.query.filter_by(UserID=user.UserID, OrderFormState="Waiting").all()
		goods = db.session.execute("select FurnitureImage,FurniturePrice,"
								   "Furniture.FurnitureID,FurnitureName, OrderItemNum from Furniture, OrderItem, OrderForm where "
								   "Furniture.FurnitureID=OrderItem.FurnitureID and OrderItem.OrderFormID=OrderForm.OrderFormID and "
								   "OrderForm.UserID=%d and OrderFormState='Waiting' " % id)
		return user, consumer, order_forms, goods
	return None, None, None, None

# test ed
@consumer_.route("/orders", methods=['GET', 'POST'])
@login_required
def consumer_orders():
	# g.user = User.query.filter_by(UserID=1).first()
	unpay = []
	review = []
	finish = []
	ulist, rlist, flist = get_allorders_byid(g.user.UserID)
	#每个商品信息
	for item in ulist:
		temp = {}
		temp['date'] = str(item[0])
		path = 'app/static/img/product/' + str(item[2]) + '.jpg'
		path_img = '/static/img/product/' + str(item[2]) + '.jpg'
		with open(path, "wb") as f:
			f.write(base64.b64decode(item[1]))
			f.close()
		temp['img'] = path_img
		temp['page'] = 'http://127.0.0.1:5000/company/furniture/' + str(item[2])
		temp['price'] = item[3]
		temp['name'] = item[4]
		temp['quantity'] = item[5]
		temp['total'] = item[5] * item[3]
		unpay.append(temp)
	unpay_num = len(unpay) + 1

	#review与unpayed格式完全相同
	for item in rlist:
		temp = {}
		temp['date'] = str(item[0])
		path = 'app/static/img/product/' + str(item[2]) + '.jpg'
		path_img = '/static/img/product/' + str(item[2]) + '.jpg'
		with open(path, "wb") as f:
			f.write(base64.b64decode(item[1]))
			f.close()
		temp['img'] = path_img
		temp['page'] = 'http://127.0.0.1:5000/company/furniture/' + str(item[2])
		temp['price'] = item[3]
		temp['name'] = item[4]
		temp['quantity'] = item[5]
		temp['total'] = item[5] * item[3]
		review.append(temp)
	review_num = len(review) + 1

	for item in flist:
		temp = {}
		temp['date'] = str(item[0])
		path = 'app/static/img/product/' + str(item[2]) + '.jpg'
		path_img = '/static/img/product/' + str(item[2]) + '.jpg'
		with open(path, "wb") as f:
			f.write(base64.b64decode(item[1]))
			f.close()
		temp['img'] = path_img
		temp['page'] = 'http://127.0.0.1:5000/company/furniture/' + str(item[2])
		temp['price'] = item[3]
		temp['name'] = item[4]
		temp['quantity'] = item[5]
		temp['total'] = item[5] * item[3]
		temp['review'] = 'Good!'
		finish.append(temp)
	finish_num = len(finish) + 1

	return render_template('consumer_order.html', unpay=unpay, unpay_num=unpay_num, review=review, review_num=review_num ,finish=finish, finish_num=finish_num, Type = g.user.UserType)

def get_allorders_byid(id):
	user = User.query.filter_by(UserID=id).first()
	if user and user.UserType == "Consumer":
		unpay = db.session.execute("select CreateTime,FurnitureImage,Furniture.FurnitureID,FurniturePrice,FurnitureName,"
								   "OrderItemNum"
								   " from OrderForm, OrderItem, Furniture where "
								   "OrderForm.OrderFormID=OrderItem.OrderFormID and OrderItem.FurnitureID="
								   "Furniture.FurnitureID and OrderFormState='Waiting' and OrderForm.UserID=%d" % id)
		review = db.session.execute(
			"select CreateTime,FurnitureImage,Furniture.FurnitureID,FurniturePrice,FurnitureName,"
			"OrderItemNum"
			" from OrderForm, OrderItem, Furniture where "
			"OrderForm.OrderFormID=OrderItem.OrderFormID and OrderItem.FurnitureID="
			"Furniture.FurnitureID and OrderFormState='Success' and OrderForm.UserID=%d and OrderForm.OrderFormID not in ("
			"select OrderFormID from Comments)" % id)
		finish = db.session.execute(
			"select CreateTime,FurnitureImage,Furniture.FurnitureID,FurniturePrice,FurnitureName,"
			"OrderItemNum"
			" from OrderForm, OrderItem, Furniture where "
			"OrderForm.OrderFormID=OrderItem.OrderFormID and OrderItem.FurnitureID="
			"Furniture.FurnitureID and OrderFormState='Success' and OrderForm.UserID=%d and OrderForm.OrderFormID in ("
			"select OrderFormID from Comments)" % id)
		return unpay, review, finish
	return None, None, None

# test ed
@consumer_.route("/decoration", methods=['GET', 'POST'])
@login_required
def consumer_decoration():
	# g.user = User.query.filter_by(UserID=1).first()
	command = []
	consumer, dec_forms = get_decform_byid(g.user.UserID)
	for item in dec_forms:
		temp = {}
		temp['command'] = item.DcFormDESC
		temp['status'] = item.DcFormState
		temp['date'] = str(item.DcFormCreateTime)
		command.append(temp)
	return render_template('consumer_decoration.html',command=command,Type = g.user.UserType)

def get_decform_byid(id):
	user = User.query.filter_by(UserID=id).first()
	if user and user.UserType == "Consumer":
		consumer = Consumer.query.filter_by(ConsumerID=user.UserID).first()
		dec_forms = DecorationForm.query.filter_by(ConsumerID=user.UserID).all()
		return consumer, dec_forms
	return None, None

app/designer/__init__.py
from .views import designer_

app/qa/__init__.py
from .views import qa_

app/qa/views.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from flask import g
from flask_login import current_user

qa_ = Blueprint('qa', __name__)

@qa_.route("/")
def qa_view():
	print 'qa views'
	g.user = current_user
	if (g.user != None and g.user.is_authenticated):
		return render_template('qa.html', Type=g.user.UserType)
	return render_template('qa.html', Type=None)

app/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask User Management</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

      <br>

      <!-- errors -->
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

app/templates/about.html
{% extends "base.html" %}

{% block title %}TYMT{% endblock %}

{% block page_content %}
		<!-- breadcrumb start -->
		<div class="breadcrumb-area">
			<div class="container">
				<ol class="breadcrumb">
				  <li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
				  <li class="active">About Us</li>
				</ol>			
			</div>
		</div>
		<!-- breadcrumb end -->	
		<!-- about-us-area-start -->
		<div class="about-us-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="about-us-page">
							<div class="about-content">
								<p>Have a cool story about how your product or service was helps change lives? Put it on your 'About Us' page. Good stories humanize your brand and provide context and meaning for your product. What's more, good stories are sticky -- which means people are more likely to connect with them and pass them on.</p>
							</div>
							<div class="about-content">
								<p>Yellow Leaf Hammocks does an amazing job of telling you about its product by describing how the hammocks empower artisan weavers and their families. The company uses acombination of words and easily digestible graphics to paint a picture, rather than using big chunks of text. They're clear about why they're different: "Not a Charity," the page reads. And then: "This is the basis for a brighter future, built on a hand up, not a handout."</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}
		

app/templates/company.html
{% extends "base.html" %}

{% block title %}
<title>MY TYMT</title>
{% endblock %}

{% block page_content %}

<div class="breadcrumb-area">
			<div class="container">
				<ol class="breadcrumb">
				  <li><a href="/company"><i class="fa fa-home"></i> Home</a></li>
				</ol>			
			</div>
		</div>

<div class = "container">
{% include "company_side.html" %}


<div class="login-area pt-30" style="margin-bottom: 30px;">
			 <div class="container">
				<div class="row">
				   <div class="centered-title text-center mb-40">
				   	
				   </div>
				   
				</div>
				<!-- /.row -->
			 </div>			
		</div>
</div>
{% endblock %}

app/templates/company_side.html
<nav class="navbar navbar-side col-lg-3 col-md-3 col-sm-6 col-xs-12 homepage_side"  style=" padding: 0px 0px 0px 0px;"role="navigation">

    <div class="sidebar-collapse">

        <ul class="nav" id="main-menu">
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('company.company_verify') }}"> &nbsp;&nbsp;MY VERIFICATION</a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('company.company_orders') }}"> &nbsp;&nbsp;MY ORDER</a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="#"> &nbsp;&nbsp;MY ADVERTISIMENT</a>
            </li>

            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('company.company_furniture_list') }}"> &nbsp;&nbsp;MY MERCHANDISE</a>
            </li>

            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('company.company_my_designer') }}"> &nbsp;&nbsp;MY DESIGNER</a>
            </li>

        </ul>

    </div>
</nav>

app/templates/consumer_side.html
<nav class="navbar navbar-side col-lg-3 col-md-3 col-sm-6 col-xs-12 homepage_side"  style=" padding: 0px 0px 0px 0px;" role="navigation">

    <div class="sidebar-collapse">

        <ul class="nav" id="main-menu">
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('consumer.consumer_cart') }}" id = "mycart"> &nbsp;&nbsp;MY CART </a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('consumer.consumer_decoration') }}" id = "decoration"> &nbsp;&nbsp;MY DECORATION</a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('consumer.consumer_change_info') }}" id = "ptofile"> &nbsp;&nbsp;MY PROFILE</a>
            </li>

            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('consumer.consumer_orders') }}" id = "myorder"> &nbsp;&nbsp;MY ORDER</a>

            </li>

            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href=""> &nbsp;&nbsp;MY REFUND</a>
            </li>

        </ul>

    </div>
</nav>

app/templates/designer_order.html
{% extends "base.html" %}

{% block title %}
<title>MY TYMT</title>
{% endblock %}

{% block page_content %}

<div class="breadcrumb-area">
			<div class="container">
				<ol class="breadcrumb">
				  <li><a href="/designer"><i class="fa fa-home"></i> Home</a></li>
				  <li class="active">MY ORDER</li>
				</ol>
			</div>
		</div>

<div class = "container">
{% include "designer_side.html" %}

<div class="account-area pt-30 log" style="width: 102%;margin-bottom: 30px;">
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-lg-9 col-sm-9">
				<div class="account-info pb-30 am-tabs" data-am-tabs>
					<ul class="am-avg-sm-2 am-tabs-nav am-nav am-nav-tabs" style="max-width:100%;width:100%">
  						<li class="am-active" style="font-size:20px;">
  							<a href="#">
  							<span class="index-needs-dt-txt">Design Order</span></a>
  						</li>
                  		<li style="font-size:20px;" >
                   			<a href="#">
                      		<span class="index-needs-dt-txt">Competitive Bid</span></a>
                  		</li>
                  		
  					</ul>



  					<div class="am-tabs-bd">
                  		<div class="am-tab-panel am-fade am-in am-active">
  							<div class="J_Brand">
  								<div class="cart-main-area pt-0">
									<div class="container">
										<div class="row">
											<div class="col-md-8 col-sm-8 col-xs-8" style="width: 70%;">
												<form action="#">				
													<div class="table-content table-responsive">
														<table>
														<thead>
														<tr>
															<th class="col-md-1 col-sm-1 col-xs-1">Date</th>
															<th class="col-md-2 col-sm-2 col-xs-2">Design Scheme</th>
															<th class="col-md-2 col-sm-2 col-xs-2">User Name</th>
															<th class="col-md-1 col-sm-1 col-xs-1">Price</th>
															
														</tr>
														</thead>
														<tbody>
														{% for item in design %}
														<tr>	
															<td >{{item['date']}}</td>
															<td ><a href={{item['url']}}>{{item['name']}}</a></td>
															<td >{{item['user']}}</td>
															<td >{{item['price']}}</td>
															
														</tr>
														{% endfor %}
														</tbody>
														</table>
													</div>
							
												</form>	
											</div>
										</div>
									</div>
								</div>
  								<div class="clear"></div>
  								<div class="clear"></div>
  							</div>
  								<div class="clear"></div>
  						</div>

  						<div class="clear"></div>

  					

  					<div class="am-tab-panel am-fade">
  							<div class="cart-main-area pt-0">
									<div class="container">
										<div class="row">
											<div class="col-md-8 col-sm-8 col-xs-8" style="width: 70%;">
												<form action="#">				
													<div class="table-content table-responsive">
														
													</div>
							
												</form>	
											</div>
										</div>
									</div>
								</div>
  							<div class="clear"></div>
  							<div class="clear"></div>
  						</div>

				</div>
			</div>
		</div>		
	</div>
</div>
</div>
</div>
{% endblock %}

app/templates/designer_side.html
<nav class="navbar navbar-side col-lg-3 col-md-3 col-sm-6 col-xs-12 homepage_side"  style=" padding: 0px 0px 0px 0px;"role="navigation">

    <div class="sidebar-collapse">

        <ul class="nav" id="main-menu">
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('designer.designer_change_info') }}"> &nbsp;&nbsp;MY PROFILE</a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('designer.designer_design_scheme') }}"> &nbsp;&nbsp;MY DESIGN</a>
            </li>
            <li style="border-right: 1px solid rgba(240, 240, 240, 1)">
            <a href="{{url_for('designer.designer_orders') }}"> &nbsp;&nbsp;MY ORDER</a>
            </li>

        </ul>

    </div>
</nav>